version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: express-jwt
    versions:
    - 0.1.3
  - dependency-name: jsonwebtoken
    versions:
    - 0.4.0
  - dependency-name: sanitize-html
    versions:
    - 1.4.2
  - dependency-name: unzipper
    versions:
    - 0.9.15
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: sanitize-html
    versions:
    - 2.3.2
  - dependency-name: file-type
    versions:
    - 16.2.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
    - 0.901.13
    - 0.901.14
  - dependency-name: "@angular/router"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.4
    - 6.6.6
  - dependency-name: "@nguniversal/express-engine"
    versions:
    - 10.0.1
    - 11.2.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: ng-mat-search-bar
    versions:
    - 9.0.1
